- name: install wartest
  hosts: all
  become: yes
  roles:
    - wartest


- name: installer wartest
  hosts: all
  become: yes

  pre_tasks:
    - name: Se connecter au registre Docker
      docker_login:
        registry_url: https://registry.gitlab.com
        username: "jfc"
        password: "glpat-hdZpoa-CoJkzc6QcDfjE"
  
  roles:
    - wartest
